### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by outgaze** [DanieL-69420/Hypixel-Stats-Tracker#1]
Add winstreak for bedwars mode, it'll calculate their winstreak based on games won and lost from the hypixel api for example if bedwars_wins:1854 changes to bedwars_wins:1855 -> ws: 0 -> 1 and if bedwars_losses:1854 to bedwars_loses:1855 -> ws: 1 -> 0

**Comment by outgaze** [comment]
Oh yeah and if you'd like multiple api keys support would be also nice

**Comment by danziel1** [comment]
Thanks for the suggestion! I'm testing out this feature on the showcase server if you want to check it out https://discord.gg/u2SDvzYXRg. I'll most likely release the update tomorrow or the day after if there's no bugs.
